import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import myphoto from '../public/myphoto.png'
import styles from '../styles/Home.module.css';
export default function Home() {
  return (
    <div className='main-bg'>
      <Head>
        <title>mzaqi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <div className='container-fluid vh-100'>
        <div className='row '>
          <div className='col-6 vh-100 d-flex align-items-center justify-content-center'>
            <Image src={myphoto} width={600} height={600}/>
          </div>
          <div className='col-6'> </div>
        </div>
      </div>
    </div>
  );
}
